name: 'GCR Login'
description: 'Login to Google Container Registry'
inputs:
  credentials_json:
    description: 'Environment'
    required: true
runs:
  using: "composite"
  steps:
    - name: Login to Google Container Registry
      uses: "google-github-actions/auth@v1"
      with:
        credentials_json: "${{ inputs.credentials_json }}"
    - name: Set up Google Cloud SDK
      uses: "google-github-actions/setup-gcloud@v1"
    - name: Configure Docker Creds
      run: |-
        gcloud auth configure-docker --quiet
      shell: bash
